sudo: false
language: python
cache: pip
python:
  - "3.6"
env:
  - BASEDIR="https://raw.githubusercontent.com/open-contracting/standard-maintenance-scripts/master"
install:
  - curl -s -S --retry 3 $BASEDIR/tests/install.sh | bash -
  - pip install -r requirements.txt
script:
  - curl -s -S --retry 3 $BASEDIR/tests/script.sh | bash -
  - pytest
